
import React from 'react';
import { Scheme, Trader, LoanProduct } from './types';

export const SCHEMES: Scheme[] = [
  {
    id: '1',
    name: 'Pradhan Mantri Krishi Sinchai Yojana',
    category: 'Irrigation',
    description: 'Per Drop More Crop. Focuses on enhancing water use efficiency at farm level through Micro Irrigation technologies.',
    eligibility: ['Area < 5 acres', 'Drip Irrigation', 'Access to water source'],
    link: 'https://pmksy.gov.in/'
  },
  {
    id: '2',
    name: 'Paramparagat Krishi Vikas Yojana (PKVY)',
    category: 'Organic',
    description: 'Promotes organic farming through the adoption of organic village by cluster approach and PGS certification.',
    eligibility: ['Farmers in a cluster', 'Willingness to adopt organic practices'],
    link: 'https://pgsindia-ncof.gov.in/'
  },
  {
    id: '3',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    category: 'Insurance',
    description: 'Provides a comprehensive insurance cover against failure of the crop thus helping in stabilising the income of the farmers.',
    eligibility: ['All farmers growing notified crops', 'Loanee and Non-Loanee farmers'],
    link: 'https://pmfby.gov.in/'
  },
  {
    id: '4',
    name: 'Kisan Credit Card (KCC) Scheme',
    category: 'Financial',
    description: 'Aims at providing adequate and timely credit support from the banking system for cultivation and other needs.',
    eligibility: ['All farmers', 'Tenant farmers', 'Oral lessees & Share Croppers'],
    link: 'https://pib.gov.in/PressReleasePage.aspx?PRID=1605658'
  }
];

export const LOAN_PRODUCTS: LoanProduct[] = [
  {
    id: 'l1',
    name: 'Kisan Credit Card (KCC)',
    type: 'Govt',
    description: 'Provides timely credit support for cultivation and other needs at a very low interest rate.',
    benefits: ['Interest subvention up to 3%', 'Flexible repayment', 'Insurance coverage'],
    eligibility: ['Owner farmers', 'Tenant farmers', 'SHGs'],
    link: 'https://www.sbi.co.in/web/agri-rural/agriculture-banking/kisan-credit-card'
  },
  {
    id: 'l2',
    name: 'NABARD Dairy Loan',
    type: 'Bank',
    description: 'Financial assistance for setting up modern dairy farms and production of clean milk.',
    benefits: ['Subsidy up to 25-33%', 'Longer tenure', 'Technical guidance'],
    eligibility: ['Individual farmers', 'NGOs', 'Cooperatives'],
    link: 'https://www.nabard.org/'
  },
  {
    id: 'l3',
    name: 'Tractor & Equipment Loan',
    type: 'FinTech',
    description: 'Fast track financing for purchasing new tractors, harvesters, and other farm machinery.',
    benefits: ['90% financing', 'Quick approval', 'Low processing fees'],
    eligibility: ['2+ acres of land', 'Stable income source'],
    link: 'https://www.mahindrafinance.com/tractor-loans'
  },
  {
    id: 'l4',
    name: 'Warehouse Receipt Financing',
    type: 'Bank',
    description: 'Loan against stored produce to prevent distress sale during market low-price periods.',
    benefits: ['Store now, sell later', 'Lower interest rates', 'Avoid middle-men'],
    eligibility: ['Produce in verified warehouse', 'Valid storage receipt'],
    link: 'https://www.hdfcbank.com/personal/borrow/popular-loans/warehouse-receipt-loan'
  }
];

export const TRADERS: Trader[] = [
  { id: '1', name: 'AgroFresh Traders', location: 'Jaipur', dealsIn: ['Wheat', 'Maize', 'Tomato'], phone: '+91 98765 43210', rating: 4.8, reviewCount: 124 },
  { id: '2', name: 'GreenLeaf Buyers', location: 'Pune', dealsIn: ['Rice', 'Sugarcane'], phone: '+91 87654 32109', rating: 4.2, reviewCount: 89 },
  { id: '3', name: 'Harvest Hub', location: 'Nagpur', dealsIn: ['Cotton', 'Soybean'], phone: '+91 76543 21098', rating: 4.5, reviewCount: 56 },
  { id: '4', name: 'FarmConnect Inc.', location: 'Jaipur', dealsIn: ['Wheat', 'Barley', 'Mustard'], phone: '+91 65432 10987', rating: 3.9, reviewCount: 42 }
];

export const TRANSLATIONS = {
  en: {
    dashboard: "KissanSevaAI Dashboard",
    subtitle: "Your complete smart farming toolkit.",
    cropDetect: "Crop Disease Detection",
    livestock: "Livestock Care",
    market: "Market Insights",
    iot: "IoT Monitoring",
    schemes: "Government Schemes",
    traders: "Traders & Buyers",
    carbon: "Carbon Credits",
    prices: "Live Market Prices",
    loans: "Loans & Credit Hub",
    loansSubtitle: "Get affordable credit, government-backed loans, and smart guidance.",
    location: "Location",
    soilType: "Soil Type",
    detect: "Detect Disease",
    analysis: "Analysis Result",
    upload: "Click to upload an image",
    farmProfile: "Your Farm Profile",
    recommendations: "Get AI Recommendations",
    smartCrop: "Smart Crop",
    carbonEstimation: "Estimate My Carbon Credits",
    callNow: "Call Now",
    officialSite: "Visit Official Site",
    search: "Search...",
    temp: "Temperature",
    humidity: "Humidity",
    moisture: "Soil Moisture",
    ph: "pH Level",
    calculateEMI: "Calculate EMI",
    checkEligibility: "Check Eligibility with AI",
    monthlyEMI: "Monthly EMI",
    totalPayable: "Total Payable",
    totalInterest: "Total Interest",
    loginTitle: "KissanSevaAI",
    loginSubtitle: "Smart solutions for modern farmers",
    emailLabel: "Email Address",
    emailPlaceholder: "farmer@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "••••••••",
    signIn: "Sign In",
    signingIn: "Signing In...",
    noAccount: "Don't have an account?",
    signUp: "Sign Up",
    forgotPassword: "Forgot Password?",
    invalidEmail: "Invalid email format",
    loginFailed: "Login failed. Please try again.",
    fullNameLabel: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    createAccount: "Create Account",
    creatingAccount: "Creating...",
    alreadyHaveAccount: "Already have an account?",
    passwordRequired: "Password is required",
    emailRequired: "Email is required",
    syncing: "Syncing Data",
    historical: "Historical Trends",
    eligibility: "Eligibility",
    apply_hint: "Generate My Report",
    voice: {
      listening: "Listening...",
      processing: "Processing...",
      filled: "Filled successfully ✅",
      error: "Speech error.",
      no_speech: "No speech detected.",
      not_detected: "Details not found.",
      failed: "Failed to parse voice.",
      speak_details: "Speak details"
    }
  },
  hi: {
    dashboard: "किसानसेवाAI डैशबोर्ड",
    subtitle: "आपका संपूर्ण स्मार्ट खेती टूलकिट।",
    cropDetect: "फसल रोग पहचान",
    livestock: "पशुधन देखभाल",
    market: "बाजार अंतर्दृष्टि",
    iot: "IoT निगरानी",
    schemes: "सरकारी योजनाएं",
    traders: "व्यापारी और खरीदार",
    carbon: "कार्बन क्रेडिट",
    prices: "लाइव बाजार भाव",
    loans: "ऋण और क्रेडिट हब",
    loansSubtitle: "सस्ती क्रेडिट, सरकारी सहायता प्राप्त ऋण और स्मार्ट मार्गदर्शन प्राप्त करें।",
    location: "स्थान",
    soilType: "मिट्टी का प्रकार",
    detect: "रोग का पता लगाएं",
    analysis: "विश्लेषण परिणाम",
    upload: "छवि अपलोड करने के लिए क्लिक करें",
    farmProfile: "आपका फार्म प्रोफाइल",
    recommendations: "AI सिफारिशें प्राप्त करें",
    smartCrop: "स्मार्ट क्रॉप",
    carbonEstimation: "मेरे कार्बन क्रेडिट का अनुमान लगाएं",
    callNow: "अभी कॉल करें",
    officialSite: "आधिकारिक साइट पर जाएं",
    search: "खोजें...",
    temp: "तापमान",
    humidity: "नमी",
    moisture: "मिट्टी की नमी",
    ph: "pH स्तर",
    calculateEMI: "ईएमआई की गणना करें",
    checkEligibility: "AI के साथ पात्रता जांचें",
    monthlyEMI: "मासिक ईएमआई",
    totalPayable: "कुल देय राशि",
    totalInterest: "कुल ब्याज",
    loginTitle: "किसानसेवाAI",
    loginSubtitle: "आधुनिक किसानों के लिए स्मार्ट समाधान",
    emailLabel: "ईमेल पता",
    emailPlaceholder: "farmer@example.com",
    passwordLabel: "पासवर्ड",
    passwordPlaceholder: "••••••••",
    signIn: "साइन इन",
    signingIn: "साइन इन हो रहा है...",
    noAccount: "खाता नहीं है?",
    signUp: "साइन अप करें",
    forgotPassword: "पासवर्ड भूल गए?",
    invalidEmail: "गलत ईमेल प्रारूप",
    loginFailed: "लॉगिन असफल। कृपया दोबारा प्रयास करें।",
    fullNameLabel: "पूरा नाम",
    fullNamePlaceholder: "अपना पूरा नाम दर्ज करें",
    createAccount: "खाता बनाएं",
    creatingAccount: "बनाया जा रहा है...",
    alreadyHaveAccount: "पहले से ही एक खाता है?",
    passwordRequired: "पासवर्ड आवश्यक है",
    emailRequired: "ईमेल आवश्यक है",
    syncing: "डेटा सिंक हो रहा है",
    historical: "ऐतिहासिक रुझान",
    eligibility: "पात्रता",
    apply_hint: "मेरी रिपोर्ट तैयार करें",
    voice: {
      listening: "सुन रहा हूँ...",
      processing: "प्रोसेसिंग...",
      filled: "सफलतापूर्वक भरा गया ✅",
      error: "वाणी त्रुटि।",
      no_speech: "कोई वाणी नहीं मिली।",
      not_detected: "विवरण नहीं मिला।",
      failed: "आवाज पहचानने में विफल।",
      speak_details: "विवरण बोलें"
    }
  },
  sa: {
    dashboard: "किसानसेवा-ए-आई फलकम्",
    subtitle: "भवतः सम्पूर्णं बुद्धिमत्कृषिसाधनपेटिका।",
    cropDetect: "सस्यरोगनिदानम्",
    livestock: "पशुपालनम्",
    market: "विपणिविवरणम्",
    iot: "IoT अनुश्रवणम्",
    schemes: "सर्वकारीययोजनाः",
    traders: "वणिक् क्रेतारश्च",
    carbon: "कार्बन-प्रत्ययः",
    prices: "प्रत्यक्ष-विपणिमूल्यम्",
    loans: "ऋण-क्रेडिट-केन्द्रम्",
    loansSubtitle: "सुलभं ऋणम्, सर्वकारीयसहायतां च प्राप्नुवन्तु।",
    location: "स्थानम्",
    soilType: "मृत्तिकाप्रकारः",
    detect: "रोगस्य अन्वेषणं कुरु",
    analysis: "विश्लेषणफलम्",
    upload: "चित्रम् आरोपयितुं नुदन्तु",
    farmProfile: "भवतः कृषिप्रलेखः",
    recommendations: "AI-परामर्शं प्राप्नुवन्तु",
    smartCrop: "बुद्धिमत्सस्यम्",
    carbonEstimation: "मम कार्बन-प्रत्ययस्य अनुमानं कुरु",
    callNow: "अधुना आह्वानं कुरु",
    officialSite: "अधिकृतजालपुटं पश्यन्तु",
    search: "अन्वेषणम्...",
    temp: "तापमानम्",
    humidity: "आर्द्रता",
    moisture: "मृत्तिका-आर्द्रता",
    ph: "pH स्तरः",
    calculateEMI: "EMI गणनां कुरु",
    checkEligibility: "AI पात्रतां पश्यन्तु",
    monthlyEMI: "मासिक-ईएमआई",
    totalPayable: "पूर्णदेयम्",
    totalInterest: "पूर्णव्याजः",
    loginTitle: "किसानसेवाAI",
    loginSubtitle: "आधुनिककृषकाणां कृते बुद्धिमत्समाधानम्",
    emailLabel: "ईमेल-पत्ता",
    emailPlaceholder: "farmer@example.com",
    passwordLabel: "कूटशब्दम्",
    passwordPlaceholder: "••••••••",
    signIn: "प्रविशतु",
    signingIn: "प्रविशति...",
    noAccount: "खाता नास्ति?",
    signUp: "पञ्जीकरणं कुरु",
    forgotPassword: "कूटशब्दं विस्मृतवान्?",
    invalidEmail: "अमान्यः ईमेल-प्रारूपः",
    loginFailed: "प्रवेशः असफलः। पुनः प्रयतस्व।",
    fullNameLabel: "पूर्णं नाम",
    fullNamePlaceholder: "स्वस्य पूर्णं नाम लिखत",
    createAccount: "खाता निर्माणं कुरु",
    creatingAccount: "निर्मियते...",
    alreadyHaveAccount: "किं पूर्वमेव खाता अस्ति?",
    passwordRequired: "कूटशब्दम् आवश्यकम्",
    emailRequired: "ईमेल आवश्यकम्",
    syncing: "तथ्यांशः समकालीक्रियते",
    historical: "ऐतिहासिकप्रवृत्तयः",
    eligibility: "पात्रता",
    apply_hint: "मम प्रतिवेदनं निर्मियताम्",
    voice: {
      listening: "शृणोमि...",
      processing: "प्रक्रिया...",
      filled: "सफलतापूर्वकं पूरितम् ✅",
      error: "वाणीदोषः।",
      no_speech: "वाणी न लब्धा।",
      not_detected: "विवरणं न प्राप्तम्।",
      failed: "वाक् विश्लेषणं विफलम्।",
      speak_details: "विवरणं वदतु"
    }
  },
  pa: {
    dashboard: "ਕਿਸਾਨ ਸੇਵਾ AI ਡੈਸ਼ਬੋਰਡ",
    subtitle: "ਤੁਹਾਡਾ ਸੰਪੂਰਨ ਸਮਾਰਟ ਫਾਰਮਿੰਗ ਟੂਲਕਿੱਟ।",
    cropDetect: "ਫਸਲਾਂ ਦੇ ਰੋਗਾਂ ਦੀ ਪਛਾਣ",
    livestock: "ਪਸ਼ੂਧਨ ਦੀ ਦੇਖਭਾਲ",
    market: "ਮਾਰਕੀਟ ਇਨਸਾਈਟਸ",
    iot: "IoT ਮਾਨੀਟਰਿੰਗ",
    schemes: "ਸਰਕਾਰੀ ਸਕੀਮਾਂ",
    traders: "ਵਪਾਰੀ ਅਤੇ ਖਰੀਦਦਾਰ",
    carbon: "ਕਾਰਬਨ ਕ੍ਰੈਡਿਟ",
    prices: "ਲਾਈਵ ਮਾਰਕੀਟ ਕੀਮਤਾਂ",
    loans: "ਕਰਜ਼ਾ ਅਤੇ ਕ੍ਰੈਡਿਟ ਹੱਬ",
    loansSubtitle: "ਕਿਫਾਇਤੀ ਕ੍ਰੈਡਿਟ ਅਤੇ ਸਰਕਾਰੀ ਕਰਜ਼ੇ ਪ੍ਰਾਪਤ ਕਰੋ।",
    location: "ਸਥਾਨ",
    soilType: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    detect: "ਰੋਗ ਦਾ ਪਤਾ ਲਗਾਓ",
    analysis: "विਸ਼ਲੇਸ਼ਣ ਨਤੀਜਾ",
    upload: "ਚਿੱਤਰ ਅਪਲੋਡ ਕਰਨ ਲਈ ਕਲਿੱਕ ਕਰੋ",
    farmProfile: "ਤੁਹਾਡਾ ਫਾਰਮ ਪ੍ਰੋਫਾਈਲ",
    recommendations: "AI ਸਿਫ਼ਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    smartCrop: "ਸਮਾਰਟ ਫਸਲ",
    carbonEstimation: "ਮੇਰੇ ਕਾਰਬਨ ਕ੍ਰੈਡਿਟ ਦਾ ਅੰਦਾਜ਼ਾ ਲਗਾਓ",
    callNow: "ਹੁਣੇ ਕਾਲ ਕਰੋ",
    officialSite: "ਅਧਿਕਾਰਤ ਸਾਈਟ 'ਤੇ ਜਾਓ",
    search: "ਖੋਜੋ...",
    temp: "ਤਾਪਮਾਨ",
    humidity: "ਨਮੀ",
    moisture: "ਮਿੱਟੀ ਦੀ ਨਮੀ",
    ph: "pH ਪੱਧਰ",
    calculateEMI: "EMI ਕੈਲਕੁਲੇਟ ਕਰੋ",
    checkEligibility: "AI ਨਾਲ ਪਾਤਰਤਾ ਚੈੱਕ ਕਰੋ",
    monthlyEMI: "ਮਾਸਿਕ EMI",
    totalPayable: "ਕੁੱਲ ਭੁਗਤਾਨ",
    totalInterest: "ਕੁੱਲ ਵਿਆਜ",
    loginTitle: "ਕਿਸਾਨਸੇਵਾAI",
    loginSubtitle: "ਆਧੁਨਿਕ ਕਿਸਾਨਾਂ ਲਈ ਸਮਾਰਟ ਹੱਲ",
    emailLabel: "ਈਮੇਲ ਪਤਾ",
    emailPlaceholder: "farmer@example.com",
    passwordLabel: "ਪਾਸਵਰਡ",
    passwordPlaceholder: "••••••••",
    signIn: "ਸਾਈਨ ਇਨ",
    signingIn: "ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...",
    noAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ?",
    signUp: "ਸਾਈਨ ਅੱਪ ਕਰੋ",
    forgotPassword: "ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?",
    invalidEmail: "ਗਲਤ ਈਮੇਲ ਫਾਰਮੈਟ",
    loginFailed: "ਲੌਗਇਨ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    fullNameLabel: "ਪੂਰਾ ਨਾਮ",
    fullNamePlaceholder: "ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    creatingAccount: "ਬਣਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    passwordRequired: "ਪਾਸਵਰਡ ਲੋੜੀਂਦਾ ਹੈ",
    emailRequired: "ਈਮੇਲ ਲੋੜੀਂਦੀ ਹੈ",
    syncing: "ਡਾਟਾ ਸਿੰਕ ਹੋ ਰਿਹਾ ਹੈ",
    historical: "ਇਤਿਹਾਸਕ ਰੁਝਾਨ",
    eligibility: "ਪਾਤਰਤਾ",
    apply_hint: "ਮੇਰੀ ਰਿਪੋਰਟ ਤਿਆਰ ਕਰੋ",
    voice: {
      listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
      processing: "ਪ੍ਰੋਸੈਸਿੰਗ...",
      filled: "ਸਫਲਤਾਪੂਰਵਕ ਭਰਿਆ ਗਿਆ ✅",
      error: "ਬੋਲਣ ਦੀ ਗਲਤੀ।",
      no_speech: "ਕੋਈ ਆਵਾਜ਼ ਨਹੀਂ ਮਿਲੀ।",
      not_detected: "ਵੇਰਵਾ ਨਹੀਂ ਮਿਲਿਆ।",
      failed: "ਆਵਾਜ਼ ਸਮਝਣ ਵਿੱਚ ਅਸਫਲ।",
      speak_details: "ਵੇਰਵੇ ਬੋਲੋ"
    }
  },
  mr: {
    dashboard: "किसानसेवाAI डॅशबोर्ड",
    subtitle: "तुमचे संपूर्ण स्मार्ट शेती टूलकिट.",
    cropDetect: "पीक रोग ओळख",
    livestock: "पशुधन काळजी",
    market: "बाजार माहिती",
    iot: "IoT मॉनिटरिंग",
    schemes: "सरकारी योजना",
    traders: "व्यापारी आणि खरेदीदार",
    carbon: "कार्बन क्रेडिट",
    prices: "थेट बाजार भाव",
    loans: "कर्ज आणि क्रेडिट हब",
    loansSubtitle: "परवडणारे कर्ज आणि सरकारी मदत मिळवा.",
    location: "स्थान",
    soilType: "मातीचा प्रकार",
    detect: "रोगाचा शोध घ्या",
    analysis: "विश्लेषण परिणाम",
    upload: "प्रतिमा अपलोड करण्यासाठी क्लिक करा",
    farmProfile: "तुमचे फार्म प्रोफाइल",
    recommendations: "एआय शिफारसी मिळवा",
    smartCrop: "स्मार्ट क्रॉप",
    carbonEstimation: "माझ्या कार्बन क्रेडिटचा अंदाज घ्या",
    callNow: "आत्ता कॉल करा",
    officialSite: "अधिकृत साइटला भेट द्या",
    search: "शोधा...",
    temp: "तापमान",
    humidity: "दमटपणा",
    moisture: "मातीचा ओलावा",
    ph: "pH पातळी",
    calculateEMI: "ईएमआय मोजा",
    checkEligibility: "AI सह पात्रता तपासा",
    monthlyEMI: "मासिक ईएमआय",
    totalPayable: "एकूण देय",
    totalInterest: "एकूण व्याज",
    loginTitle: "किसानसेवाAI",
    loginSubtitle: "आधुनिक शेतकऱ्यांसाठी स्मार्ट उपाय",
    emailLabel: "ईमेल पत्ता",
    emailPlaceholder: "farmer@example.com",
    passwordLabel: "पासवर्ड",
    passwordPlaceholder: "••••••••",
    signIn: "साइन इन",
    signingIn: "साइन इन होत आहे...",
    noAccount: "खाते नाही का?",
    signUp: "साइन अप करा",
    forgotPassword: "पासवर्ड विसरलात?",
    invalidEmail: "चुकीचे ईमेल स्वरूप",
    loginFailed: "लॉगिन अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    fullNameLabel: "पूर्ण नाव",
    fullNamePlaceholder: "तुमचे पूर्ण नाव प्रविष्ट करा",
    createAccount: "खाते तयार करा",
    creatingAccount: "तयार होत आहे...",
    alreadyHaveAccount: "आधीच खाते आहे?",
    passwordRequired: "पासवर्ड आवश्यक आहे",
    emailRequired: "ईमेल आवश्यक आहे",
    syncing: "डेटा सिंक होत आहे",
    historical: "ऐतिहासिक ट्रेंड",
    eligibility: "पात्रता",
    apply_hint: "माझा अहवाल तयार करा",
    voice: {
      listening: "ऐकत आहे...",
      processing: "प्रक्रिया करत आहे...",
      filled: "यशस्वीरित्या भरले गेले ✅",
      error: "वाणी त्रुटी.",
      no_speech: "कोणताही आवाज आढळला नाही.",
      not_detected: "तपशील सापडले नाहीत.",
      failed: "आवाज विश्लेषणात अपयश.",
      speak_details: "तपशील बोला"
    }
  }
};
